### PR TITLE
Update TUSClient.swift

### PR DESCRIPTION
**Pull request by pathakmanvendu**

### CODE REVIEW

**Comment by Acconut** [comment]
Could you briefly explain what this change is about?

**Comment by pathakmanvendu** [comment]
Hi . I was using this library and got an error message and to remove that
we need to change one line in the TUSClient.
Add self keyword.

**Comment by Acconut** [comment]
Thanks. @donnywals, could you have a look at this?

**Comment by pathakmanvendu** [comment]
Hi!  Can you help me to understand and implement this library more?

**Comment by donnywals** [comment]
Hi @pathakmanvendu on which Xcode version are you seeing an error with this? The need to add `self` in places where `self` has been unwrapped hasn't been there since Swift 5.8. I'm not opposed to adding this for legacy Xcode version support, just curious to see which Xcode version our users or on.

On the note of understanding and implementing, yes we can help. Please open an issue with your questions and we can take it from there.

**Comment by donnywals** [comment]
Please open a GH issue with something that's a little bit more specific. We have a sample app and some getting started docs that you can explore to see what's going on.

I'll happily update and expand the docs but a "more clear example" is a bit sparse to go of. We have a functioning sample app that I would refer to as the clearest example we can give because it showcases all the features we have.

**Pull request merged**
