### PR TITLE
Fix missing custom fields for network request header

### PR DESCRIPTION
**Pull request by m3t8d1tr**
The backend expects a set of specific fields and fails the request without them.

### CODE REVIEW

**Comment by m3t8d1tr** [comment]
You need to update the swift-development branch to match the current master with version 3...

**Comment by Acconut** [comment]
Why don't you open the PR to merge into master? the swift-development branch is not used anymore.

**Comment by m3t8d1tr** [comment]
@Acconut Well I will open PR into master. But in your pull request guide wrote swift-development branch how target branch.

**Comment by Acconut** [comment]
> But in your pull request guide wrote swift-development branch as target branch.

Thank you, that's a mistake and I just updated the docs!

@tursunovic The previous maintainer used the `develop` and `swift-development` branch for active development and then merged them into master for each release. I think you prefer to directly develop on master (just like we do for all other tus repositories). So I updated the guide to tell people to always open PRs to master: https://github.com/tus/TUSKit/commit/637ba2d553027878d01915bd644c530f2896e855

Let me know if you prefer it the other way.

**Comment by Acconut** [comment]
New PR at https://github.com/tus/TUSKit/pull/143.

**Pull request closed without merging**
