### PR TITLE
2.1.0

### PR DESCRIPTION
**Pull request by MMasterson**
#88

### CODE REVIEW

**Comment by MMasterson** [comment]
Set to go live this weekend.

**Comment by hannojg** [comment]
Just wanted to leave a note, that we use these changes in our app and deployed it to internal testing. None of our test users have yet reported any issues with uploading (everything works smooth, also cases like "the user tried to upload during bad internet, lost the connection, hours later opened the app with wifi --> files were uploaded (resume ability works)).
So, just wanted to say: I consider these changes to be safe.

**Comment by r-a-o** [comment]
Is this PR, 2.1.0 based on TUS protocol version 2.0? If so, does it require server side TUS version to be upgraded to 2.0 protocol? or will this client work with TUS server 1.0 protocol as well? 

Also, do we have App Extension support in 2.1.0? We used to have this in objc version. 

Thanks!

**Comment by MMasterson** [comment]
hey @r-a-o 

This is for 1.0 of the protocol, there is no need for the server side to be upgraded at all. 

Can you point me in a bit of direction as to what youre trying to do with App Extensions? thanks!

**Comment by r-a-o** [comment]
Hi @MMasterson 👋🏼
My App's share extension does file upload (images and video) similar to how social apps' share extensions work(fb,tw,ig etc) 
Uploaded asset is shared with a message on the user's account.

**Pull request merged**
