### PR TITLE
Clean up + error handling

### PR DESCRIPTION
**Pull request by justin-distaulo**
Fixed some warnings, cleaned up error handling, Swiftified some code, added some comments/documentation, cleaned up TUSUpload model.

### CODE REVIEW

**Comment by justin-distaulo** [comment]
@MMasterson I've done a bit of clean up. Let me know what you think.

**Comment by MMasterson** [comment]
hey @justin-distaulo, thanks for the PR! I have to walk through this one a bit more before merging, I'll let you know if I have any comments or questions

**Comment by MMasterson** [comment]
@justin-distaulo why was there removal of the Singleton?

**Comment by MMasterson** [comment]
also the branch to merge into would be `swift-development`

**Comment by justin-distaulo** [comment]
Hey @MMasterson, these last 3 commits were not intended for this PR but rather for use with a personal project. Sorry about that. I'll move them onto another branch ASAP.

**Comment by MMasterson** [comment]
okay cool, and I read the previous commits, they look great. I appreciate you going through and making those fixes/additions!

**Comment by MMasterson** [comment]
closing because many other PRs that have either cleared some of these up, or progressed the files where there are too many conflicts. Feel free to reopen if you've made it against the current branch!

**Pull request closed without merging**
