### PR TITLE
Feature/background support + resume-ability

### PR DESCRIPTION
**Pull request by hannojg**
This PR is built on top of https://github.com/tus/TUSKit/pull/87

Added proper background handling for uploads. There are two possibilities to build upload with good background support in iOS:
1. Use (https://developer.apple.com/documentation/foundation/urlsession/1411550-uploadtask)[uploadTask from file and let the system handle the upload
2. Schedule an action with https://developer.apple.com/documentation/uikit/uiapplication/1623051-beginbackgroundtask

As this library creates `Data` chunks and uses `uploadTask` from `data` I used the second approach. To use the first approach we would need to write each chunk to a file and let the system upload this file chunk which felt like "doing too much".

If you look in the `TUSExecutor` you will find a new method called `uploadInBackground` which starts the uploading as background tasks.
In addition to that I added a new config option called `backgroundMode`, which has two modes:
* (Default): PreferFinishUpload
  * It means that it tries to finish the current upload task and then stop. This is prefered, as its more likely to finish one upload than the whole queue. Plus it is more battery-friendly, as the app will spend less time processing in the background.
* PreferUploadQueue
  *  This tries to upload everything that is in the queue even if the app goes into the background.

### Other things I've done along the way:

- Fixed that cleanup removes correct upload
- Fixed that on failure the queue stopped (otherwise it would be in "uploading" state and you have to reset the app)
- Fixed issue where queue kept adding the same element to itself
- Fixed a crash when reporting progress
- Implemented cancel
- Fixed that instead of moving the file to the `TUS` dir for upload it _copies_ the file (imagine a user specifies a file from files and the file gets moved, lol)

### CODE REVIEW

**Comment by MMasterson** [comment]
Hey @hannojg thanks for the PR

Moved the branch to the develop branch, where a few things are different and implemented. I appreciate you taking the time to run through these. Will take a look and get it in. Please take a look at the conflicts and will ask questions if needed!

**Comment by hannojg** [comment]
Leaving this as a note for myself: we should add a "best practice" section in the readme to not use `andData`. Why? Because when adding multiple uploads with data they get written each time to the preferences/NSUserDefaults, which has a size limit of ~4MB (which can easily be exceeded by the data). [Thinking of this as there seems to be a conflict with the line where I changed from `andData` to `andFile`]

**Comment by MMasterson** [comment]
@hannojg We changed back to storing data and files to the file system, but I see in `TUSUpload` where it was overlooked and stored in `UserDefaults` for state tracking. Maybe we simply remove that store, and turn any data into a file from the `TUSUpload` initialization as well? 

I like the idea of adding a Best Practices section. 

And yes I'll add a contribution templated and update the README

**Comment by hannojg** [comment]
Fixed the merge conflicts! Yeah, by not using `UserDefaults` anymore this problem is probably being avoided 😊

**Comment by MMasterson** [comment]
@hannojg I wasn't suggesting removing UserDefaults as a whole, just storing this property
https://github.com/tus/TUSKit/blob/89360b773857035dc8f76006298b922592687968/TUSKit/Classes/TUSUpload.swift#L45
and updating this initializer to create a file based off the data 
https://github.com/tus/TUSKit/blob/89360b773857035dc8f76006298b922592687968/TUSKit/Classes/TUSUpload.swift#L75

I think UserDefaults does a nice job with states of uploads and queue when the app exits and reopens. Thoughts?

**Comment by hannojg** [comment]
Ah okay, I think that's a good idea. I also was about to do the same but wasn't sure if I would break something unexpectedly 😄 
> I think UserDefaults does a nice job with states of uploads and queue when the app exits and reopens. Thoughts?
To be honest, I am not a native iOS/Swift developer, so I have no real opinion on that. It seems to work good, right? 😄

**Comment by hannojg** [comment]
Don't want to rush this on you, I just want to ask kindly if there is anything missing to get this merged?

**Comment by hannojg** [comment]
There is still another issue (which is not related to the changes here) that when the user closes the app, while the uploads are running, the queue doesn't update its state from uploading -> ready which will it cause to stall on the next opening of the app (the only way I see to fix this from a user perspective is to uninstall the app).
I am working on a fix for this, but there seem to be some issues in terms of the resume-ability of the previously running uploads. (I think TUSKit does not yet implement the protocol correctly, be e.g. doing upfront a `head` request to see where the current `contentOffset` is - about to fix this)

**Comment by hannojg** [comment]
Okay, two features I implemented:
- Handle when the app gets closed to cancel all current uploads
- Implemented resume-ability, meaning that the cancelled uploads can be resumed

See this video (this wasn't possible before):

https://user-images.githubusercontent.com/16821682/109398345-ad742200-793c-11eb-8ec2-3db26031dd22.mp4

> I scheduled 3 images for uploading. The first is (immediately) uploaded. During the upload of the second image, I force close the app. The two pending uploads are now cancelled. When reopening the app, I clicked on `Upload`, which called `resumeAll`. The upload that was aborted gets resumed where it left off.

## Overview of the changes:

### Resume-ability

The resume-ability is achieved by following the [core protocol specifications](https://tus.io/protocols/resumable-upload.html#core-protocol).

**TUSUpload:**

- The `TUSUpload` has now a `prevState` field. This is needed because when we set the state to e.g. `canceled` we don't know whether the upload was in `new`/`creating`/`uploading` state which is a piece of crucial information to continue the uploading at the right point
  - This `prevState` never gets overwritten by `canceled`, `paused`
  https://github.com/hannojg/TUSKit/blob/acacf21d40e70f7a371c76f80d15b89b95bab88d/TUSKit/Classes/TUSUpload.swift#L55-L66
- I added an extension `TUSUpload+getData` which just gets the `[Data]` array from the file 

**TUSExecutor:**

- I refactored several functions to extensions, namely:
  - `TUSExecutor+checkForResumableOffset` - This contains a function that returns the offset from where the upload should start. It does a `HEAD` request to the uploading URL to get the `Upload-Offset`
    - We don't rely on the `TUSUpload.uploadOffset` for two reasons: 1) The local upload offset and the one on the server can be different which would cause issues, 2) the protocol asks client implementations to do it this way
  - `TUSExecutor+get`- Here I just moved this download `get` function to the extension to keep the executor clean
  - `TUSExecutor+Utility` - Collection of utility functions. Currently just contains the `dataIntoChunks` function.
- The public method on the `TUSExecutor` to start the uploading process is now called `uploadInBackground`. This is because the uploads are scheduled by default in the background (which is recommended by the apple developer guidelines to directly start work that could move potentially into the background directly in the background)
  - It accepts a `TUSUpload` object and additionally a second bool param called `skipResumeCheck`. This is only `true` when the executors `create` calls upload, and it skips the check for getting a potential upload offset from the server to speed up the upload.
https://github.com/hannojg/TUSKit/blob/acacf21d40e70f7a371c76f80d15b89b95bab88d/TUSKit/Classes/TUSExecutor.swift#L94-L99
- There is a new `prepareUpload` function that gets the chunks for uploading (by using the `checkForResumableOffset` function). When retrieving all information it calls a callback param with the chunks for uploading.
https://github.com/hannojg/TUSKit/blob/acacf21d40e70f7a371c76f80d15b89b95bab88d/TUSKit/Classes/TUSExecutor.swift#L110-L121

**TUSClient:**

- Listening to `applicationWillTerminate` events using notification-center, which will cancel all uploads & set the queue to ready
https://github.com/hannojg/TUSKit/blob/acacf21d40e70f7a371c76f80d15b89b95bab88d/TUSKit/Classes/TUSClient.swift#L85-L100
- When `createOrResume` an upload, comparing the current state against the previous state, and eventually reset the state to the previous state so the upload can proceed correctly:
https://github.com/hannojg/TUSKit/blob/acacf21d40e70f7a371c76f80d15b89b95bab88d/TUSKit/Classes/TUSClient.swift#L138-L147

### Noteworthy edge case

Handling of an edge case where the app gets terminated at the very moment the last byte chunk was uploaded, but the app didn't call the completion block of the URLRequest, yet.
This is solved by comparing the `Upload-Offset` and the `Content-Length` header when checking from where to resume the upload. If they are equal we immediately call success:
First, in `prepareUpload`:
https://github.com/hannojg/TUSKit/blob/acacf21d40e70f7a371c76f80d15b89b95bab88d/TUSKit/Classes/TUSExecutor.swift#L144-L149
Which callbacks to the background execution:
https://github.com/hannojg/TUSKit/blob/acacf21d40e70f7a371c76f80d15b89b95bab88d/TUSKit/Classes/TUSExecutor.swift#L99-L104

## Other considerations

Some thoughts after this implementation/refactoring:

- I haven't tested whether `pauseAll` (which calls just cancelAll?) and then calling `resumeAll` works as a "library end user" would expect it (just needs testing). I can imagine that we shouldn't just set the state of uploads to `cancel` when the user expects `pause` -> that probably needs some refactoring
- I don't understand why the global progress doesn't work. It should reduce all `currentUploads` together, but instead it always "emits" state as if we were tracking the progress of just one upload

-----

Thank you for reading until here ❤️ I guess going through all these changes (and words) will require some time and I appreciate this in advance. I truly believe that with these changes the TUSKit becomes greater. I was trying to integrate the TUSKit into our production app but without these changes, I can't really provide the experience of our user's demand.
happy to provide any help to get this merged/changed 🚀

**Comment by MMasterson** [comment]
@hannojg 

Thank you so much for this PR. Very detailed and puts a lot of work in to get the library up to protocol standards. Internal offset/state tracking was used for resuming but of course, the more TUS way is the way to go, which you seem to have crushed. And fixing up some state tracking on close is very nice.  Many of these things have been on my list for a while now, but with my workload at my day job I haven't been able to make these additions. I'm glad you decided to contribute your work.


As for your considerations

> I haven't tested whether pauseAll (which calls just cancelAll?) and then calling resumeAll works as a "library end user" would expect it (just needs testing). I can imagine that we shouldn't just set the state of uploads to cancel when the user expects pause -> that probably needs some refactoring

> I don't understand why the global progress doesn't work. It should reduce all currentUploads together, but instead it always "emits" state as if we were tracking the progress of just one upload

I'll take a look at this and see if I can find anything

> I was wondering whether there should be an "auto-resume" functionality when the app restarts? Currently, the library user could implement this on his/her own by just calling resumeAll. This makes it opt-in and thus should probably require updating the docs.

I think we should not do an auto-resume, but update the README on how to achieve it. This gives the ability for developers to decide when to resume and not force them into it

> Having tests for the TUSExecutor would be quite useful. When I implement edge case handling I feel always better to have tests that ensure that in the future everything will work as expected. Unfortunately, I have never written a test in swift, don't know how to mock nor anything, lol.

I'll write some more tests here!

**Pull request merged**
