### PR TITLE
Add an implementation to fetch previous uploads

### PR DESCRIPTION
**Pull request by kiyosoft**
add a feature to get the previous uploads #155

### CODE REVIEW

**Comment by kiyosoft** [comment]
I name it findPreviousUploads to make it consistent with the tus-js-client but giving it more generic name makes more sense. As you said lets change the `PreviousUpload` to `UploadInfo`, but for the `getUploadInfo` it is more like a single value return function but we expect a list of UploadInfos. @donnywals  can you suggest another name for this?

**Comment by donnywals** [comment]
Fair point on the info vs infos. Maybe we could do something like `getPendingUploads()`, `getStoredUploads()` or something like that. I think on the method name the `Info` part can be implied

**Comment by kiyosoft** [comment]
`getStoredUploads()` looks good to me. I will change and update the PR shortly

**Comment by donnywals** [comment]
I will merge this today and prepare a new release on Monday. You can go ahead and point to main as a dependency until then

**Pull request merged**
