### PR TITLE
Upload only mode

### PR DESCRIPTION
**Pull request by alikaragoz**
Hey there,

I don't really know if this is a relevant PR for everyone but in our current project we need to make the file creation call on our API (which does the tus call). We need to do that because we want to track the uploads and eventually clean them if they are not used anymore. This also gives more flexibility in using tus overall.

In order to do that I created a new `createUploadFromFile` method with takes an `uploadUrl` and sets the `state` to `TUSResumableUploadStateUploadingFile` which make the loop jump to the upload step.

Again, let me know if you have any questions, open to any remarks.
Ali

### CODE REVIEW

**Comment by alikaragoz** [comment]
To give a little bit more context. We have our app API and we have Cloudflare's upload API. Our main usage with tus is with cloudflare.

In order to control the cost and delete non used videos/files from cloudflare, we need to make the file create call to our API (which it itself doing the create file call to cloudflare). Our API logs the file in a DB giving us a way to track and delete files that are not used and can be deleted.

**Comment by MMasterson** [comment]
Hey @alikaragoz,

So if I'm understanding correctly, you need to be able to supply a different URL for each upload, instead of using the URL set during the initialization of the `TUSSession` object?

```self.tusSession = [[TUSSession alloc] initWithEndpoint:[[NSURL alloc] initWithString:UPLOAD_ENDPOINT] dataStore:uploadStore allowsCellularAccess:YES];```

Doesn't seem to hurt to add the kinda of flexibility. Can you provide an example of how this would look implemented?

**Comment by alikaragoz** [comment]
Hey @MMasterson,

As you may already know, in order make an upload, we need to do an upload creation call, a `POST` which is giving us the `Location` URL where to initiate the actual upload. Once we have this Location we can do a `PATCH` and start uploading the content.

This PR allow us to skip the upload creation (`POST`) and directly go to the upload part (`PATCH`) with a different URL than the `UPLOAD_ENDPOINT`.

In practice we only have this variation in the creation of the `TUSResumableUpload` object:
```objc
TUSResumableUpload *upload = [self.tusSession createUploadFromFile:fileUrl 
                                                           headers:@{} 
                                                          metadata:@{}
                                                         uploadUrl:UPLOAD_URL];
```

Where `UPLOAD_URL` is the `Location` obtained via the `POST` on our backend.

The change itself is quite small but gives us some flexibility.

Hope I've been clear.
Ali

**Comment by MMasterson** [comment]
Yep, all understood! Simply adding a way to have a 3rd party create the file outside of the current TUSKit manner. 

I read through and all looks good! 

I just need to add an example and then I can release the new version.

**Comment by alikaragoz** [comment]
You got it 👌🏼
Thank you for your work 🙏🏻

**Comment by MMasterson** [comment]
thank you!

**Pull request merged**
